[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "etl-production-pipeline"
version = "0.1.0"
description = "ETL pipeline for oil & gas production data (Prefect)"
authors = [
    { name="Alejandro Perez", email="you@example.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"

# â† AquÃ­ agregas tus dependencias si quieres instalar sin requirements.txt
dependencies = [
    "pandas",
    "prefect",
    "sqlalchemy",
    "psycopg2-binary",
    "numpy",
    "python-dotenv"
]

[tool.black]
line-length = 88

[tool.setuptools.packages.find]
where = ["src"]  # ğŸ”¥ hace que "from src...." funcione siempre
